---
# This playbook will install mysql and create db user and give permission.

- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server
    - python-mysqldb


- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
   - restart mysql

- name: Start Mysql Service
  shell: echo "hello"
  notify:
   - restart mysql

- name: Create Application Database
  mysql_db: name="hello" state=present

- name: Create Application DB User
  mysql_user: name="hello" password="hello" priv=*.*:ALL host='%' state=present

